---

- name: Install python-software-properties
  action: apt pkg=python-software-properties state=present

- name: Install python-pycurl
  apt: pkg={{ item }} state=installed
  with_items:
   - python-pycurl

- name: Add nginx ppa
  action: apt_repository repo=ppa:nginx/stable state=present

- name: Install nginx
  action: apt pkg=nginx state=installed
  notify:
    - restart nginx

- name: Create the directories for site specific configurations
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "conf.d"

- name: Copy the nginx configuration file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
   - restart nginx

- name: Copy the nginx default configuration file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Copy the nginx default site configuration file
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Create the link for site enabled specific configurations
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: Create the configurations for sites
  template: src=site.j2 dest=/etc/nginx/conf.d/{{ item['server']['file_name'] }}.conf
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
  notify:
   - reload nginx

- name: start the nginx service
  service: name=nginx state=started enabled=yes

